### ISSUE TITLE
README mentions Knowledge Base

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/hyper_admin#18]
![screen shot 2014-09-21 at 15 33 44](https://cloud.githubusercontent.com/assets/378235/4348607/fe2cc978-4193-11e4-8b9a-2ec0b87fb08d.png)

**Comment by sindrenm** [comment]
This is a bit weird. It's true, but still not entirely correct to put in here. Thanks. :smiley:

**Comment by sindrenm** [comment]
There. 87c2284913fb9cdb3cd4c1ac87c3348a53278a3d fixed it. :grinning:

**Comment by timkurvers** [comment]
:+1:

**Comment by sindrenm** [comment]
Thanks for noticing. :smiley:
