### ISSUE TITLE
Validations aren't known to Angular

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/hyper_admin#2]
It would be neat to have Angular know about how each field is validated, so that we could do some actual client-side validation. The way it is know, Rails will return a set of error messages which Angular will display in and above the form. If the form is invalid, we shouldn't even need to bother Rails with trying to validate anything.

**Comment by SteveBenner** [comment]
Check out https://github.com/hyperoslo/hyper_admin/pull/25
