### ISSUE TITLE
Refactor the whole state registration stuff

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/hyper_admin#9]
States are being registered when the application first loads through the `Resource.registerStates` function. It's quite a mess and it relies on the state provider (`$stateProvider` from UI Router) to be available on the global `window` object, which is even more messy. However, I have found no sane way to build up the states dynamically based on which resources are available.

Maybe we don't have to, though. Maybe we can do some clever URL matching and get away with predefined states for each view, regardless of the name of the resource? Something like this:

``` coffeescript
$stateProvider
  .state "index",
    url: "/admin/:pluralName"
    templateUrl: (params) ->
      "/admin/#{params.pluralName}.html"
    controller: "IndexCtrl as indexCtrl"
    data:
      resource: resource
  .state "index.new",
    url: "/new"
    templateUrl: (params) ->
      "/admin/#{params.pluralName}/new.html"
    controller: "NewCtrl as newCtrl"
    data:
      resource: resource
      mode: "new"
  .state "index.show",
    url: "/:id"
    templateUrl: (params) ->
      "/admin/#{params.pluralName}/#{params.id}.html"
    controller: "ShowCtrl as showCtrl"
    data:
      resource: resource
  .state "index.edit",
    url: "/:id/edit"
    templateUrl: (params) ->
      "/admin/#{params.pluralName}/#{params.id}/edit.html"
    controller: "EditCtrl as editCtrl"
    data:
      resource: resource
      mode: "edit"
```

That might totally work. I think. I'll have to give it a try.

**Comment by sindrenm** [comment]
Oh. But then of course, where do I get that `resource` from?

**Comment by sindrenm** [comment]
Maybe if I do a `resolve`?

**Comment by sindrenm** [comment]
This stuff seems to work! Just … a little … bit … more now.

**Comment by sindrenm** [comment]
And there we have it: deed570.

**Comment by jgorset** [comment]
![This guy](http://i.imgur.com/Evdwm.gif)
